apiVersion: v2
name: mapproxy
description: A Helm chart for mapproxy service
type: application
version: 1.8.4
appVersion: 1.8.4
dependencies:
  - name: nginx
    version: 1.3.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm
